# Generated by Django 5.2.12 on 2026-05-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('doctor', 'Doctor Import'), ('medicine', 'Medicine Import'), ('pricing', 'Pricing Import')], db_index=True, help_text='Category of data being imported.', max_length=20)),
                ('file_name', models.CharField(help_text='Original filename as uploaded by the user.', max_length=255)),
                ('total_rows', models.PositiveIntegerField(default=0, help_text='Total data rows seen in the file (header row excluded).')),
                ('success_rows', models.PositiveIntegerField(default=0, help_text='Rows successfully written to the database.')),
                ('failed_rows', models.PositiveIntegerField(default=0, help_text='Rows that failed validation or DB write.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Overall outcome of the import job.', max_length=10)),
                ('error_log', models.TextField(blank=True, default='', help_text='Human-readable summary of errors encountered during the import. Populated from ImportResult.summary() and per-row RowError strings.')),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
