# Generated by Django 5.2.12 on 2026-04-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('hospital', models.CharField(blank=True, help_text='Hospital or clinic name.', max_length=300)),
                ('location', models.CharField(blank=True, help_text='City / area / region.', max_length=300)),
                ('mode', models.CharField(choices=[('prepaid', 'Prepaid'), ('postpaid', 'Postpaid')], db_index=True, default='prepaid', help_text='Prepaid = has investment & ROI tracking. Postpaid = track sales only.', max_length=10)),
                ('doctor_type', models.CharField(choices=[('trade', 'Trade'), ('hospital', 'Hospital'), ('stocking', 'Stocking')], db_index=True, default='trade', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_rep', models.ForeignKey(blank=True, help_text='Sales representative assigned to this doctor.', limit_choices_to={'role': 'rep'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medicines', to='doctors.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_medicines', to='medicines.medicine')),
            ],
            options={
                'verbose_name': 'Doctor–Medicine Mapping',
                'verbose_name_plural': 'Doctor–Medicine Mappings',
                'ordering': ['doctor__name', 'medicine__name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='doctors', through='doctors.DoctorMedicine', to='medicines.medicine'),
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Investment amount in currency.', max_digits=12)),
                ('roi_ratio', models.DecimalField(decimal_places=2, help_text='ROI multiplier (e.g. 2.5 means 2.5× return expected).', max_digits=6)),
                ('start_date', models.DateField(help_text='Date from which this investment is active.')),
                ('notes', models.TextField(blank=True, help_text='Optional remarks about this investment.')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
                'ordering': ['-start_date'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='doctormedicine',
            constraint=models.UniqueConstraint(fields=('doctor', 'medicine'), name='unique_doctor_medicine'),
        ),
    ]
