# Generated by Django 5.2.12 on 2026-05-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(blank=True, db_index=True, help_text='Contact email address.', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, help_text='Contact phone number.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, help_text="Doctor's medical specialization.", max_length=150, null=True),
        ),
    ]
