# Generated by Django 4.2 on 2026-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_email_doctor_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', help_text='Lifecycle status of the investment ROI.', max_length=20),
        ),
    ]
