# Generated by Django 4.2 on 2026-06-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_investment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpaidDoctor',
            fields=[
            ],
            options={
                'verbose_name': 'Postpaid Doctor',
                'verbose_name_plural': 'Postpaid Doctors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doctors.doctor',),
        ),
        migrations.CreateModel(
            name='PrepaidDoctor',
            fields=[
            ],
            options={
                'verbose_name': 'Prepaid Doctor',
                'verbose_name_plural': 'Prepaid Doctors',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('doctors.doctor',),
        ),
    ]
