# Generated by Django 5.2.12 on 2026-04-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Generic / trade name of the medicine.', max_length=200)),
                ('brand', models.CharField(blank=True, help_text='Brand / manufacturer label.', max_length=200)),
                ('ptr', models.DecimalField(decimal_places=2, help_text='Price To Retailer — used for sales value calculation.', max_digits=10, verbose_name='PTR')),
                ('pts', models.DecimalField(decimal_places=2, help_text='Price To Stockist (reference).', max_digits=10, verbose_name='PTS')),
                ('mrp', models.DecimalField(decimal_places=2, help_text='Maximum Retail Price (reference).', max_digits=10, verbose_name='MRP')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Inactive medicines are hidden from new entries.')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
