# Generated by Django 4.2 on 2026-05-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='ptr',
            field=models.DecimalField(decimal_places=2, help_text='Price To Retailer (reference).', max_digits=10, verbose_name='PTR'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='pts',
            field=models.DecimalField(decimal_places=2, help_text='Price To Stockist — used for sales value calculation.', max_digits=10, verbose_name='PTS'),
        ),
    ]
