# Generated by Django 5.2.12 on 2026-04-01 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Number of units sold.')),
                ('entry_date', models.DateField(db_index=True, help_text='Date of the sales transaction.')),
                ('notes', models.TextField(blank=True, help_text='Optional remarks about this entry.')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries', to='doctors.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries', to='medicines.medicine')),
                ('rep', models.ForeignKey(help_text='Sales representative who recorded this entry.', limit_choices_to={'role': 'rep'}, on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Entry',
                'verbose_name_plural': 'Sales Entries',
                'ordering': ['-entry_date', '-created_at'],
                'abstract': False,
            },
        ),
    ]
