# Generated by Django 5.2.12 on 2026-05-04 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('medicines', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpaidEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('roi_percentage', models.DecimalField(decimal_places=2, help_text='ROI percentage for this postpaid entry.', max_digits=6)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount owed for this postpaid ROI entry.', max_digits=12)),
                ('is_paid', models.BooleanField(db_index=True, default=False, help_text='Whether this entry has been paid.')),
                ('payment_date', models.DateField(blank=True, help_text='Date of payment, if paid.', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks about this postpaid entry.')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpaid_entries', to='doctors.doctor')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpaid_entries', to='medicines.medicine')),
            ],
            options={
                'verbose_name': 'Postpaid Entry',
                'verbose_name_plural': 'Postpaid Entries',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
