# Generated by Django 5.2.12 on 2026-05-04 05:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_postpaid_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidentry',
            name='end_date',
            field=models.DateField(blank=True, help_text="End of date range (required for 'range' payout type).", null=True),
        ),
        migrations.AddField(
            model_name='postpaidentry',
            name='payout_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Month (1–12) for monthly payout type.', null=True),
        ),
        migrations.AddField(
            model_name='postpaidentry',
            name='payout_type',
            field=models.CharField(choices=[('range', 'Date Range'), ('monthly', 'Monthly'), ('campaign', 'Campaign')], db_index=True, default='campaign', help_text='Scope used to compute the payout amount.', max_length=10),
        ),
        migrations.AddField(
            model_name='postpaidentry',
            name='payout_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year for monthly payout type.', null=True),
        ),
        migrations.AddField(
            model_name='postpaidentry',
            name='start_date',
            field=models.DateField(blank=True, help_text="Start of date range (required for 'range' payout type).", null=True),
        ),
        migrations.AlterField(
            model_name='postpaidentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Auto-calculated: scoped sales value × ROI%.', max_digits=12),
        ),
    ]
