# Generated by Django 5.2.12 on 2026-05-15 05:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('medicines', '0001_initial'),
        ('sales', '0003_add_payout_scope_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidentry',
            name='total_sales_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Snapshot of the total sales value used to compute amount.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='postpaidentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, help_text='Auto-calculated on creation: scoped sales value × ROI%. Frozen after first save.', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='postpaidentry',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_type', 'range')), fields=('doctor', 'medicine', 'payout_type', 'start_date', 'end_date'), name='unique_postpaid_range'),
        ),
        migrations.AddConstraint(
            model_name='postpaidentry',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_type', 'monthly')), fields=('doctor', 'medicine', 'payout_type', 'payout_month', 'payout_year'), name='unique_postpaid_monthly'),
        ),
        migrations.AddConstraint(
            model_name='postpaidentry',
            constraint=models.UniqueConstraint(condition=models.Q(('payout_type', 'campaign')), fields=('doctor', 'medicine', 'payout_type'), name='unique_postpaid_campaign'),
        ),
    ]
