# Generated by Django 5.2.12 on 2026-05-15 05:52

from decimal import Decimal
from django.db import migrations, models


def migrate_is_paid_to_payment_status(apps, schema_editor):
    """
    Convert existing is_paid boolean to the new payment_status field.

    is_paid=True  → payment_status='paid', paid_amount=amount
    is_paid=False → payment_status='unpaid', paid_amount=0
    """
    PostpaidEntry = apps.get_model("sales", "PostpaidEntry")

    # Fully paid entries: set status and copy amount → paid_amount
    PostpaidEntry.objects.filter(is_paid=True).update(
        payment_status="paid",
    )
    # For paid entries, set paid_amount = amount (row-by-row for F() support)
    for entry in PostpaidEntry.objects.filter(is_paid=True):
        PostpaidEntry.objects.filter(pk=entry.pk).update(
            paid_amount=entry.amount,
        )

    # Unpaid entries: explicitly set (defaults handle this, but be explicit)
    PostpaidEntry.objects.filter(is_paid=False).update(
        payment_status="unpaid",
        paid_amount=Decimal("0"),
    )


def reverse_payment_status_to_is_paid(apps, schema_editor):
    """Reverse: convert payment_status back to is_paid boolean."""
    PostpaidEntry = apps.get_model("sales", "PostpaidEntry")
    PostpaidEntry.objects.filter(payment_status="paid").update(is_paid=True)
    PostpaidEntry.objects.exclude(payment_status="paid").update(is_paid=False)


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_postpaid_financial_integrity'),
    ]

    operations = [
        # Step 1: Add new fields (is_paid still exists at this point)
        migrations.AddField(
            model_name='postpaidentry',
            name='paid_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0'),
                help_text='Actual amount paid so far. May be less than amount for partial payments.',
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name='postpaidentry',
            name='payment_status',
            field=models.CharField(
                choices=[
                    ('unpaid', 'Unpaid'),
                    ('partial', 'Partially Paid'),
                    ('paid', 'Fully Paid'),
                ],
                db_index=True,
                default='unpaid',
                help_text='Payment lifecycle: unpaid → partial → paid.',
                max_length=10,
            ),
        ),

        # Step 2: Migrate existing data
        migrations.RunPython(
            migrate_is_paid_to_payment_status,
            reverse_payment_status_to_is_paid,
        ),

        # Step 3: Remove the old boolean field
        migrations.RemoveField(
            model_name='postpaidentry',
            name='is_paid',
        ),

        # Step 4: Update payment_date help text
        migrations.AlterField(
            model_name='postpaidentry',
            name='payment_date',
            field=models.DateField(
                blank=True,
                help_text='Date of the most recent payment.',
                null=True,
            ),
        ),
    ]
