# Generated by Django 5.2.12 on 2026-05-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_payment_status_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidentry',
            name='is_legacy_calculation',
            field=models.BooleanField(default=False, help_text='Protects historical payouts from recalculation after PTR→PTS migration.'),
        ),
    ]
