# Generated by Django 5.2.12 on 2026-05-21 10:33

from django.db import migrations


def set_legacy_calculation_true(apps, schema_editor):
    PostpaidEntry = apps.get_model('sales', 'PostpaidEntry')
    PostpaidEntry.objects.all().update(is_legacy_calculation=True)

def set_legacy_calculation_false(apps, schema_editor):
    PostpaidEntry = apps.get_model('sales', 'PostpaidEntry')
    PostpaidEntry.objects.all().update(is_legacy_calculation=False)

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_postpaidentry_is_legacy_calculation'),
    ]

    operations = [
        migrations.RunPython(set_legacy_calculation_true, set_legacy_calculation_false),
    ]
