# Generated by Django 4.2 on 2026-05-25 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_investment_status'),
        ('sales', '0007_protect_legacy_payouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesentry',
            name='investment',
            field=models.ForeignKey(blank=True, help_text='Investment this sales entry belongs to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_entries', to='doctors.investment'),
        ),
    ]
