# Generated by Django 4.2 on 2026-05-29 07:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicines', '0002_alter_medicine_ptr_alter_medicine_pts'),
        ('doctors', '0003_investment_status'),
        ('sales', '0010_backfill_salesentry_snapshots'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpaidCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked'), ('partial', 'Partial'), ('settled', 'Settled')], db_index=True, default='open', max_length=10)),
                ('total_sales_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpaid_campaigns', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Postpaid Campaign',
                'verbose_name_plural': 'Postpaid Campaigns',
                'ordering': ['-year', '-month', 'doctor__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PostpaidSaleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('pts_at_sale', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('value_at_sale', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('commission_percentage_at_sale', models.DecimalField(decimal_places=2, editable=False, max_digits=6)),
                ('commission_at_sale', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('entry_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_entries', to='sales.postpaidcampaign')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postpaid_sales', to='medicines.medicine')),
                ('rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postpaid Sale Entry',
                'verbose_name_plural': 'Postpaid Sale Entries',
                'ordering': ['-entry_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.postpaidcampaign')),
            ],
            options={
                'verbose_name': 'Campaign Payment',
                'verbose_name_plural': 'Campaign Payments',
                'ordering': ['-payment_date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='postpaidcampaign',
            constraint=models.UniqueConstraint(fields=('doctor', 'month', 'year'), name='unique_campaign_month_year'),
        ),
    ]
