# Generated by Django 4.2.30 on 2026-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_postpaidcampaign_postpaidsaleentry_campaignpayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpaidcampaign',
            name='commission_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='postpaidcampaign',
            name='status',
            field=models.CharField(choices=[('awaiting_commission', 'Awaiting Commission'), ('open', 'Open'), ('partial', 'Partial'), ('settled', 'Settled'), ('locked', 'Locked')], db_index=True, default='awaiting_commission', max_length=20),
        ),
    ]
