# Generated by Django 4.2 on 2026-06-01 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0012_alter_postpaidcampaign_commission_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpaidsaleentry',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name': 'Postpaid Sale', 'verbose_name_plural': 'Postpaid Sales'},
        ),
        migrations.AlterModelOptions(
            name='salesentry',
            options={'ordering': ['-entry_date', '-created_at'], 'verbose_name': 'Prepaid Sale', 'verbose_name_plural': 'Prepaid Sales'},
        ),
        migrations.AddField(
            model_name='postpaidcampaign',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_campaigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postpaidcampaign',
            name='settlement_attachment',
            field=models.FileField(blank=True, null=True, upload_to='settlements/'),
        ),
        migrations.AddField(
            model_name='postpaidcampaign',
            name='settlement_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postpaidcampaign',
            name='settlement_reason',
            field=models.CharField(blank=True, choices=[('WRITE_OFF', 'Write-off (Approved deviation)'), ('DISPUTE', 'Resolved Dispute'), ('PROMOTIONAL_SUPPORT', 'Promotional Support'), ('MANAGEMENT_APPROVAL', 'Management Approval'), ('DATA_CORRECTION', 'Data Correction'), ('OTHER', 'Other (Reason in Notes)')], max_length=50, null=True),
        ),
    ]
